
help:
	@echo "run - the application with no args"
	@echo "simple-json - run the application with simple-json example:  '{"test":"value"}'"

run:
	go run .

simple-json:
	go run . -p '{"test":"value"}'

empty-json:
	go run . -p '{}'


test:
	go test ./...
